### ISSUE TITLE
Migrate communication from Discord to FOSS Mattermost

### ISSUE THREAD

**Issue by alltheseas** [Bitcoin-Product-Community/proposals#10]
## Description of Proposal
Bitcoin Product Community is an open source product community that runs on Discord as of April 2023. This proposal is to migrate from Discord to a FOSS tool in Mattermost. Reasoning is laid below.

As Jeff Booth lays out in The Price of Tomorrow (and in his talks such as [BTC Van 4/20/23](https://youtu.be/4flAOQSs8ks?t=1603)) the inevitable outcome of the fiat system will tend towards total control on communication. This means that BPC may eventually become pressured, and/or deplatformed. Discord is after all a platform, where imperfect people make decisions.

In contrast to using a platform, one of the most successful FOSS projects in [BTCPayServer](https://github.com/btcpayserver/) run by luminaries such as [Pavlenex](https://twitter.com/pavlenex/status/1496533885538160652), [Rockstar](https://iris.to/rockstar), and [Dorier](https://twitter.com/nicolasdorier/status/898378514256207872) utilize a FOSS communication solution in [Mattermost](https://chat.btcpayserver.org/).

A FOSS solution is aligned with the values & principles of the FOSS BTC Product Community (BPC). Mattermost extends access to those who do not want to expose, or those without phone numbers, removes the friction of requiring a phone number, blocking basic privacy protection tools in email forwarders & VPNs. BTCPayServer is proof that a FOSS communication solution scales over thousands of users, and is fit for purpose in accommodating the growing BPC. 

Pros of the current setup:
-Discord is well known, and widely distributed
-The BPC community is already using Discord, and it seems to work for most
-There is zero effort in continuing to use the same tool (and there is no additional effort in setting up a new tool)

Cons:
-Discord is not an open source project
-Risk of deplatforming: Discord has investors, and may eventually IPO. This means that Discord is beholden to external interests, and is run by imperfect people.
-Discord discourages user privacy by requiring a phone number, and by not allowing email forwarders, VPNs
-VPN friction breaks discord for some users
-Phone number requirements may dissuade some from joining

## Deadline for Rough Consensus
June 1st, 2023

Notes for the community:: 
- Please feel free to leave comments on the issue for any questions or concerns. 
- Vote with Emojis on the issue proposal.
    - :thumbsup: in support, 
    - :thumbsdown: not in support

**Comment by alltheseas** [comment]
@pavlenex can you share your feedback as you use both solutions 🙏

**Comment by ecurrencyhodler** [comment]
Hey alltheseas. Thanks for such your proposal. I think if we were launching the community again, we would've seriously considered it as an option. But since we've already launched, the lift to migrate communities would be herculean and we'd lose a lot of people. 

If we were being deplatformed, that would provide a strong impetus for people to move to mattermost. But I think right now with so many social media platforms the typical bitcoiner has: TG/TW/Discord/Nostr/Signal, adding another one like mattermost would be a huge disincentive. Plus people won't likely use it if that's the only reason they use the app as our frequency of communication is about once a week.

So this is a nACK for me.

**Comment by imyjimmy** [comment]
moving communities around is a hard coordination game. maybe if we get cancelled on discord--let's see how it plays out first?

**Comment by pavlenex** [comment]
> @pavlenex can you share your feedback as you use both solutions 🙏

Main reasoning for the proposed move is software not being open-source and having a single point if failure. Mattermost indeed fixes the first thing, but the second thing is just wishful thinking, it needs to be hosted on a VPS, and your provider can also shut you down. It requires updating, maintianing from time to time, which without a good dev to take care of that is tricky; we at btcpay have a dev who handles this, I'm afraid we really don't have such person that I am aware who can take care of the servers.

But the first reason for NACK is that I am really tired of "chat platform" battles, in every foss community there's at least once a year discussion about a different platform, everyone has their own preferences, and unless there's a real need to move, I just don't see why we should.

**Comment by bitcoinprecept** [comment]
I like the spirit of the proposal and personally have the bias of disliking discord. 

That said, I've never heard of mattermost and don't feel particularly concerned about this group being deplatformed. Even if we were, I think the group could spontaneously reform and replan rapidly just based on connections on Twitter, Nostr etc. 

Good suggestion but nACK for me. I'll happily follow along if we do move though!

**Comment by ecurrencyhodler** [comment]
This proposal has not passed.
