### ISSUE TITLE
Create a Bitcoin FOSS Opportunity Board

### ISSUE THREAD

**Issue by ecurrencyhodler** [Bitcoin-Product-Community/proposals#14]
## Description of Proposal
Since we launched the group on March 20, 2023, one of the initiatives we've been working on has been to connect contributors to foss bitcoin projects (#8).

Since then we've been manually interviewing both foss projects and contributors to get a feel for what exactly is the "secret sauce" of connecting the two groups. Here's our [product requirements document(PRD)](https://docs.google.com/document/d/1AQTCdnM1zh3BYIckGEAoQbSDmCUHrj6gMfth-3mrTwM/edit?usp=sharing) that explains our methodology.

You can find the results of our interviews and market research in [this slide deck](https://docs.google.com/presentation/d/1Tu_UIPUHN-OPRlfz3qv3S0wik1eH0x7XoAH034-sBWU/edit#slide=id.p). You can also listen to the high level overview of the results of the initiative in [this video](https://www.youtube.com/watch?v=s4axCp5yBWo).

We are now ready to move on to the next phase of creating an MVP which is the Bitcoin FOSS Opportunity Board. This board will be a repo under our Github organization that FOSS projects can submit an issue with the [following template](https://docs.google.com/document/d/1M6Q8QqGYZq_aLkMqUDc6K-ikI0xJN1oE1kK5JPvBD3c/edit?usp=sharing). Once they create an issue, it will automatically get put in a github project titled: Bitcoin FOSS Opportunity Board. This is the place contributors can peruse to see which opportunity and project they are interested in getting involved with.

We decided to use github for several reasons. It's free and easy to set up which is great for an MVP. But most importantly this is the tool most FOSS Bitcoin projects use. It is also great for skill development for contributors as they get familiar with github. 

If we have no objections, we should create this repo + github project then start marketing it to Bitcoin FOSS projects who might need some help.

Here is the [project folder](https://drive.google.com/drive/folders/1zQBG4wYKT6T-FnC7m0r4qdNfWEkGKAAr?usp=sharing) which contains all the interviews we did, the templates, the PRD, and the data. 

## Deadline for Rough Consensus
5/11/23

Notes for the community:: 
- Please feel free to leave comments on the issue for any questions or concerns. 
- Vote with Emojis on the issue proposal.
    - :thumbsup: in support, 
    - :thumbsdown: not in support

**Comment by alltheseas** [comment]
Looks good! 

Suggestion:
If known, FOSS projects should clearly list where exactly they need help, and what expectations are.

**Comment by ecurrencyhodler** [comment]
@alltheseas thanks! And good suggestion. I outlined the issue template that FOSS projects would fill out in this [google doc](https://docs.google.com/document/d/1M6Q8QqGYZq_aLkMqUDc6K-ikI0xJN1oE1kK5JPvBD3c/edit). Does this address your concern?
