### ISSUE TITLE
Weekly meetings for bolt.fun participants

### ISSUE THREAD

**Issue by ecurrencyhodler** [Bitcoin-Product-Community/proposals#17]
## Description of Proposal
Bolt.fun and Fedi is hosting a bitcoin + AI hackathon. This is a great opportunity for people aspiring to be a bitcoin PM to get experience and come out with a project. 

We can host weekly meetings for people participating in the hackathon so that we can support each other. 

We will need to discuss what a good timezone is but I propose Thursdays at 9:30AM PT. But comment below if you think of a better time slot for you.

Here is a link to the hackathon with more details: https://bolt.fun/tournaments/ai4all/overview

## Deadline for Rough Consensus
7/3/23 Short timeline because the hackathon already started. Also their first kickoff call is that day at 8am PT: https://www.youtube.com/watch?v=I9RMay6ZKL8

Notes for the community:: 
- Please feel free to leave comments on the issue for any questions or concerns. 
- Vote with Emojis on the issue proposal.
    - :thumbsup: in support, 
    - :thumbsdown: not in support

**Comment by Cli5y** [comment]
I'm happy to support with this!
