### ISSUE TITLE
Create a list of learning materials for becoming a product manger

### ISSUE THREAD

**Issue by iglesiasbrandon** [Bitcoin-Product-Community/proposals#7]
## Description 

Persona: People who want to be product managers

For folks who want to develop skills in product management who might not know the value or steps to becoming one. How might we provide them with a path to embark on?

Possible Solutions
Create a list of useful articles, links, videos and other materials that someone can consume in order to become a open source product/project manager.

## Resources:
N/A

NOTE:
Issue originally submitted by Johns Beharry on hellonext

**Comment by iglesiasbrandon** [comment]
Comment from Santos Hernandez on hellonext.

`Hey, I was thinking about posting a curated course on [emeralize.app](http://emeralize.app/) using resources that I used to get my first job as a Product Owner and Product Manager. I can set that up pretty quickly.`

**Comment by iglesiasbrandon** [comment]
Comment from a.assoiants on hellonext.

`Love it - might be helpful to mine for common questions and concerns people have transitioning into the discipline. Could be a meeting or simple thread.`

**Comment by ecurrencyhodler** [comment]
Here is an mvp of this initiative: https://bitcoin-product.org/Recommended-Reading-603de8c8b52847a2bf918d379ba040f7
